title: "Sajeevan Jeyakumar"
logo: "/assets/img/your-logo.png"
description: "Machine Learning Engineer | AI Enthusiast | Developer"
theme: jekyll-theme-minimal

# Optional social links
github_username: sajeevan-jeyakumar
linkedin_username: sajeevan-jeyakumar
email: sajeevan@example.com

# Project settings
show_downloads: false
